<?php

use Drupal\Core\Url;

/**
 * Implements @see hook_toolbar.
 */
function wienimal_editor_toolbar_toolbar(): array
{
    $items = [];
    $config = \Drupal::config('wienimal_editor_toolbar.settings');
    $versionInfo = \Drupal::service('wienimal_editor_toolbar.version_info');

    if (!$config->get('menu_items.version_info.enable')) {
        return $items;
    }

    if (!$info = $versionInfo->get()) {
        return $items;
    }

    $items['build_info'] = [
        '#type' => 'toolbar_item',
        'tab' => [
            '#type' => 'link',
            '#title' => sprintf('%s (%s)', $info['version'], $info['date']->format('d/m/y - h:i')),
            '#url' => Url::fromUserInput('/version.json'),
            '#attributes' => [
                'title' => t('Version'),
                'class' => ['toolbar-icon', 'toolbar-icon-version', 'toolbar-item', 'toolbar-item--version'],
            ],
        ],
        '#weight' => 1000,
        '#wrapper_attributes' => [
            'class' => ['toolbar-tab--version'],
        ],
    ];

    return $items;
}

/**
 * Implements @see hook_toolbar_alter.
 */
function wienimal_editor_toolbar_toolbar_alter(array &$items): void
{
    $builder = \Drupal::service('wienimal_editor_toolbar.menu_builder');

    if (!$builder->showToolbar()) {
        return;
    }

    $items['administration']['tray']['toolbar_administration']['#pre_render'] = [
        [$builder, 'preRenderTray'],
    ];
}

/**
 * Implements @see hook_locale_translation_projects_alter
 */
function wienimal_editor_toolbar_locale_translation_projects_alter(array &$projects): void
{
    $path = drupal_get_path('module', 'wienimal_editor_toolbar') . '/translations/%language.po';
    $projects['wienimal_editor_toolbar']['info']['interface translation server pattern'] = $path;
}

/**
 * Implements @see hook_menu_links_discovered_alter
 */
function wienimal_editor_toolbar_menu_links_discovered_alter(array &$links): void
{
    $config = \Drupal::config('wienimal_editor_toolbar.settings');

    if (!$config->get('menu_items.content_overview.enable')) {
        unset($links['wienimal_editor_toolbar.content_overview']);
    }

    if (!$config->get('menu_items.content_add.enable')) {
        unset($links['wienimal_editor_toolbar.content_add']);
    }

    if ($config->get('menu_items.content_add.enable')) {
        if (isset($links['admin_toolbar_tools.extra_links:node.add'])) {
            unset($links['admin_toolbar_tools.extra_links:node.add']);
            $links = array_filter($links, static function (array $link) {
                return !isset($link['parent'])
                    || $link['parent'] !== 'admin_toolbar_tools.extra_links:node.add';
            });
        }

        if (isset($links['admin_toolbar_tools.add_content'])) {
            unset($links['admin_toolbar_tools.add_content']);
        }
    }
}
